#!/bin/bash
data/kraken-actions/extract_action_strings data/kraken-actions
itstool -o kraken.pot data/kraken.xml.in
xgettext -c --join-existing --from-code=UTF-8 --keyword=_ --keyword=N_ --output=kraken.pot \
    src/*.c libkraken-extension/*.c libkraken-private/*.c eel/*.c

xgettext -c --join-existing  -L Python data/kraken-actions/action_i18n_strings.py generate_additional_file --output=kraken.pot
xgettext -c --join-existing  -L Glade gresources/kraken-bookmarks-window.glade --output=kraken.pot
xgettext -c --join-existing  -L Glade gresources/kraken-desktop-overlay.glade --output=kraken.pot
xgettext -c --join-existing  -L Glade gresources/kraken-desktop-preferences.glade --output=kraken.pot
xgettext -c --join-existing  -L Glade gresources/kraken-file-management-properties.glade --output=kraken.pot
xgettext -c --join-existing  -L Glade gresources/kraken-search-bar.glade --output=kraken.pot
xgettext -c --join-existing  -L Glade gresources/*.ui --output=kraken.pot
xgettext -c --join-existing  -L Glade gresources/kraken-action-layout-editor.glade --output=kraken.pot
xgettext -c --join-existing  -L Python action-layout-editor/*.py --output=kraken.pot
